services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-airflow:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    networks:
      - default
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    command: >
      bash -c "airflow db init &&
            airflow db upgrade &&
            airflow db migrate &&
            airflow users create --username airflow --password password --firstname John --lastname Doe --role Admin --email admin@example.com"

  airflow-webserver:
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    build: .
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
      AIRFLOW__WEBSERVER__DEFAULT_USER: ${AIRFLOW__WEBSERVER__DEFAULT_USER}
      AIRFLOW__WEBSERVER__DEFAULT_PASSWORD: ${AIRFLOW__WEBSERVER__DEFAULT_PASSWORD}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8080:8080"
    volumes:
      - /home/jtsarmento/.dbt:/opt/airflow/.dbt
      - ./dags:/opt/airflow/dags
      - ./dags/scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    command: webserver

  airflow-scheduler:
    user: "${AIRFLOW_UID}:${AIRFLOW_GID}"
    build: .
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
      DBT_PROFILES_DIR: ${DBT_PROFILES_DIR}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - /home/jtsarmento/.dbt:/opt/airflow/.dbt
      - ./dags:/opt/airflow/dags
      - ./dags/scripts:/opt/airflow/scripts
      - ./dbt_project:/opt/airflow/dbt_project
    command: scheduler

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    depends_on:
      - postgres
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/superset/superset_config.py
      - superset_home:/app/superset_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset-init:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset-init
    depends_on:
      - postgres
      - superset
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    volumes:
      - ./superset_config.py:/app/superset/superset_config.py
      - superset_home:/app/superset_home
    command: >
      bash -c "superset db upgrade &&
               superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
               superset init"
    restart: on-failure

volumes:
  postgres_data:
  airflow_logs:
  superset_home:
