-- models/staging/stg_public_school_characteristics.sql

{{ config(
    materialized='view'
) }}

SELECT
    CAST("OBJECTID" AS INTEGER) AS objectid,
    "NCESSCH"::TEXT AS ncessch,
    "SURVYEAR"::TEXT AS survyear,
    "STABR"::TEXT AS stabbr,
    "LEAID"::TEXT AS leaid,
    "ST_LEAID"::TEXT AS st_leaid,
    "LEA_NAME"::TEXT AS lea_name,
    "SCH_NAME"::TEXT AS sch_name,
    "LSTREET1"::TEXT AS lstreet1,
    "LSTREET2"::TEXT AS lstreet2,
    "LCITY"::TEXT AS lcity,
    "LSTATE"::TEXT AS lstate,
    "LZIP"::TEXT AS lzip,
    "LZIP4"::TEXT AS lzip4,
    "PHONE"::TEXT AS phone,
    "CHARTER_TEXT"::TEXT AS charter_text,
    "VIRTUAL"::TEXT AS virtual,
    "GSLO"::TEXT AS gslo,
    "GSHI"::TEXT AS gshi,
    "SCHOOL_LEVEL"::TEXT AS school_level,
    "STATUS"::TEXT AS status,
    "SCHOOL_TYPE_TEXT"::TEXT AS school_type_text,
    "SY_STATUS_TEXT"::TEXT AS sy_status_text,
    "ULOCALE"::TEXT AS ulocale,
    "NMCNTY"::TEXT AS nmcnty,
    "CNTY"::TEXT AS cnty,
    "TOTFRL"::INTEGER AS totfrl,
    "FRELCH"::INTEGER AS frelch,
    "REDLCH"::INTEGER AS redlch,
    "DIRECTCERT"::INTEGER AS directcert,
    "PK"::INTEGER AS pk,
    "KG"::INTEGER AS kg,
    "G01"::INTEGER AS g01,
    "G02"::INTEGER AS g02,
    "G03"::INTEGER AS g03,
    "G04"::INTEGER AS g04,
    "G05"::INTEGER AS g05,
    "G06"::INTEGER AS g06,
    "G07"::INTEGER AS g07,
    "G08"::INTEGER AS g08,
    "G09"::INTEGER AS g09,
    "G10"::INTEGER AS g10,
    "G11"::INTEGER AS g11,
    "G12"::INTEGER AS g12,
    "G13"::INTEGER AS g13,
    "UG"::INTEGER AS ug,
    "AE"::INTEGER AS ae,
    "TOTMENROL"::INTEGER AS totmenrol,
    "TOTFENROL"::INTEGER AS totfenrol,
    "TOTAL"::INTEGER AS total,
    "MEMBER"::INTEGER AS member,
    "FTE"::NUMERIC AS fte,
    "STUTERATIO"::NUMERIC AS stuteratio,
    "AMALM"::INTEGER AS amal_m,
    "AMALF"::INTEGER AS amal_f,
    "AM"::INTEGER AS am,
    "ASALM"::INTEGER AS asal_m,
    "ASALF"::INTEGER AS asal_f,
    "AS_"::INTEGER AS as_,
    "BLALM"::INTEGER AS blal_m,
    "BLALF"::INTEGER AS blal_f,
    "BL"::INTEGER AS bl,
    "HPALM"::INTEGER AS hpal_m,
    "HPALF"::INTEGER AS hpal_f,
    "HP"::INTEGER AS hp,
    "HIALM"::INTEGER AS hial_m,
    "HIALF"::INTEGER AS hial_f,
    "HI"::INTEGER AS hi,
    "TRALM"::INTEGER AS tral_m,
    "TRALF"::INTEGER AS tral_f,
    "TR"::INTEGER AS tr,
    "WHALM"::INTEGER AS whal_m,
    "WHALF"::INTEGER AS whal_f,
    "WH"::INTEGER AS wh,
    "LATCOD"::NUMERIC AS latcod,
    "LONCOD"::NUMERIC AS loncod
FROM {{ source('public', 'public_school_characteristics') }}
